public class ThrowTest { // 主程式
	public static void main(String[] args) { // 例外處理程式敘述
		try { // 取得參數字串
			int value = Integer.parseInt(args[0]);  //從外部引入參數
			if (value == 0)
				// 丟出ArithmeticException例外
				throw new ArithmeticException("值為0"); //()內表示參數值輸入0,在Run->Run Configurations->Argument可輸入參數值
		}

		catch (ArithmeticException e) { // 處理ArithmeticException例外
			System.out.println("例外說明: " + e.getMessage()); //getMassage(函式庫內建方法)表示取得有問題的地方
			System.out.print("例外原因: ");
			e.printStackTrace();
		} finally {
			System.out.println("錯誤處理結束");
		}

		System.out.println("main");
	}
}
